version: '3.8'

services:
  backend:
    build: ./
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./client
    ports:
      - "3000:3000"
      
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
